<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows 7" host="RAZOO-3"><DocLocation><![CDATA[D:\QTP_RAZOO\QTP_Razoo_JSIssue\JSIssue]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[JSIssue]]></DName>
<Res><![CDATA[Res88]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:29]]></Time>
<TimeTick>1308740609</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://www-qaindia.razoo.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:29]]></Time>
<TimeTick>1308740609</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" nType="Navigate to http://www-qaindia.razoo.com/" Source="Action1" SourceLine="33" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:30]]></Time>
<TimeTick>1308740610</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="34" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:33]]></Time>
<TimeTick>1308740613</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:33]]></Time>
<TimeTick>1308740613</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Sign up.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:33]]></Time>
<TimeTick>1308740613</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" Source="Action1" SourceLine="36" >
<Disp><![CDATA[Sign up.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[user[first_name].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hp"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:33]]></Time>
<TimeTick>1308740613</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="21" Source="Action1" SourceLine="37" >
<Disp><![CDATA[user[first_name].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[user[last_name].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Razoo"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:33]]></Time>
<TimeTick>1308740613</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="24" Source="Action1" SourceLine="38" >
<Disp><![CDATA[user[last_name].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[user[email].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["HpRazoo3@sra.com"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:33]]></Time>
<TimeTick>1308740613</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" Source="Action1" SourceLine="39" >
<Disp><![CDATA[user[email].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[user[terms_of_use].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:34]]></Time>
<TimeTick>1308740614</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" Source="Action1" SourceLine="40" >
<Disp><![CDATA[user[terms_of_use].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[user[password].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["4d39500247e1c78f77baa294e7edeaa36c4a"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:34]]></Time>
<TimeTick>1308740614</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" Source="Action1" SourceLine="41" >
<Disp><![CDATA[user[password].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[user[password_confirmation].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["4d395005e7a35e3aba599d613c99e159ce4b"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:34]]></Time>
<TimeTick>1308740614</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="Action1" SourceLine="42" >
<Disp><![CDATA[user[password_confirmation].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Create Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:34]]></Time>
<TimeTick>1308740614</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="39" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Create Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[donate > Find and support.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:34]]></Time>
<TimeTick>1308740614</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="42" Source="Action1" SourceLine="44" >
<Disp><![CDATA[donate > Find and support.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" Source="Action1" SourceLine="36" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:34]]></Time>
<TimeTick>1308740614</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" Source="Action1" SourceLine="47" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:37]]></Time>
<TimeTick>1308740617</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="46" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:37]]></Time>
<TimeTick>1308740617</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["kw"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=text<br>name=kw<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=kw<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=parametricKeyword<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>max length=2147483647<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>default value=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>rows=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:37]]></Time>
<TimeTick>1308740617</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="50" Source="Action1" SourceLine="49" >
<Disp><![CDATA["kw"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[kw.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TEST ORG1 WITH EIN3"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:37]]></Time>
<TimeTick>1308740617</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="51" Source="Action1" SourceLine="49" >
<Disp><![CDATA[kw.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[kw.Submit]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:38]]></Time>
<TimeTick>1308740618</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="54" Source="Action1" SourceLine="50" >
<Disp><![CDATA[kw.Submit]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[TEST ORG1 WITH EIN3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:38]]></Time>
<TimeTick>1308740618</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" Source="Action1" SourceLine="51" >
<Disp><![CDATA[TEST ORG1 WITH EIN3.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="49" Source="Action1" SourceLine="49" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:38]]></Time>
<TimeTick>1308740618</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" Source="Action1" SourceLine="55" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:33:41]]></Time>
<TimeTick>1308740621</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="61" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:02]]></Time>
<TimeTick>1308740642</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["donation[amount]"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:02]]></Time>
<TimeTick>1308740642</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="105" status="Warning" Source="Action1" SourceLine="57" >
<Disp><![CDATA["donation[amount]"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["donation[amount]"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=text<br>name=order_user_order[donations_attributes][0][amount]<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=order_user_order[donations_attributes][0][amount]<SPAN class=Failed> (Skipped)</SPAN><br>html id=donation_amount<SPAN class=Failed> (Skipped)</SPAN><br>max length=2147483647<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>default value=30.00<SPAN class=Failed> (Skipped)</SPAN><br>class=<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>rows=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:02]]></Time>
<TimeTick>1308740642</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="106" Source="Action1" SourceLine="57" >
<Disp><![CDATA["donation[amount]"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[donation[amount].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["30"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:02]]></Time>
<TimeTick>1308740642</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="107" Source="Action1" SourceLine="57" >
<Disp><![CDATA[donation[amount].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Donate.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:02]]></Time>
<TimeTick>1308740642</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="110" Source="Action1" SourceLine="58" >
<Disp><![CDATA[Donate.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="104" status="Warning" Source="Action1" SourceLine="57" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:02]]></Time>
<TimeTick>1308740642</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="112" Source="Action1" SourceLine="61" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:05]]></Time>
<TimeTick>1308740645</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="114" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:07]]></Time>
<TimeTick>1308740647</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[donation[amount].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["30.00"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:07]]></Time>
<TimeTick>1308740647</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="118" Source="Action1" SourceLine="63" >
<Disp><![CDATA[donation[amount].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[order_user_order[credit_card_a_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hp Razoo"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:07]]></Time>
<TimeTick>1308740647</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="121" Source="Action1" SourceLine="64" >
<Disp><![CDATA[order_user_order[credit_card_a_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[order_user_order[credit_card_a.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Wood RidgeDrive"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="124" Source="Action1" SourceLine="65" >
<Disp><![CDATA[order_user_order[credit_card_a.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[order_user_order[credit_card_a_3.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Washington DC"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="127" Source="Action1" SourceLine="66" >
<Disp><![CDATA[order_user_order[credit_card_a_3.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[order_user_order[credit_card_a_4.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Washington"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="130" Source="Action1" SourceLine="67" >
<Disp><![CDATA[order_user_order[credit_card_a_4.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[order_user_order[credit_card_a_5.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["20001"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="133" Source="Action1" SourceLine="68" >
<Disp><![CDATA[order_user_order[credit_card_a_5.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[order_user_order[credit_card_a_6.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5555555555554444"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="136" Source="Action1" SourceLine="69" >
<Disp><![CDATA[order_user_order[credit_card_a_6.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[order_user_order[credit_card_a_7.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="139" Source="Action1" SourceLine="70" >
<Disp><![CDATA[order_user_order[credit_card_a_7.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Donate Now.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="142" Source="Action1" SourceLine="71" >
<Disp><![CDATA[Donate Now.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="117" Source="Action1" SourceLine="63" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:08]]></Time>
<TimeTick>1308740648</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="144" Source="Action1" SourceLine="75" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:11]]></Time>
<TimeTick>1308740651</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="146" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:14]]></Time>
<TimeTick>1308740654</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[No Thanks.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:14]]></Time>
<TimeTick>1308740654</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="150" Source="Action1" SourceLine="77" >
<Disp><![CDATA[No Thanks.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[My account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:15]]></Time>
<TimeTick>1308740655</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="153" Source="Action1" SourceLine="78" >
<Disp><![CDATA[My account.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="149" Source="Action1" SourceLine="77" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:15]]></Time>
<TimeTick>1308740655</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="155" Source="Action1" SourceLine="81" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:18]]></Time>
<TimeTick>1308740658</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="157" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:18]]></Time>
<TimeTick>1308740658</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[My Profile.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:18]]></Time>
<TimeTick>1308740658</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="161" Source="Action1" SourceLine="83" >
<Disp><![CDATA[My Profile.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="160" Source="Action1" SourceLine="83" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:18]]></Time>
<TimeTick>1308740658</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="163" Source="Action1" SourceLine="86" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:21]]></Time>
<TimeTick>1308740661</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="165" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:21]]></Time>
<TimeTick>1308740661</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[My Donations.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:21]]></Time>
<TimeTick>1308740661</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="169" Source="Action1" SourceLine="88" >
<Disp><![CDATA[My Donations.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="168" Source="Action1" SourceLine="88" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:21]]></Time>
<TimeTick>1308740661</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="171" Source="Action1" SourceLine="91" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:24]]></Time>
<TimeTick>1308740664</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="173" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:24]]></Time>
<TimeTick>1308740664</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Account Settings.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:24]]></Time>
<TimeTick>1308740664</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="177" Source="Action1" SourceLine="93" >
<Disp><![CDATA[Account Settings.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="176" Source="Action1" SourceLine="93" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:24]]></Time>
<TimeTick>1308740664</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="179" Source="Action1" SourceLine="96" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:27]]></Time>
<TimeTick>1308740667</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="181" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:27]]></Time>
<TimeTick>1308740667</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[My Saved Cards.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:27]]></Time>
<TimeTick>1308740667</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="185" Source="Action1" SourceLine="98" >
<Disp><![CDATA[My Saved Cards.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="184" Source="Action1" SourceLine="98" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/22/2011 - 16:34:27]]></Time>
<TimeTick>1308740667</TimeTick>