<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="" host="RAZOO-1"><DocLocation><![CDATA[D:\QTP_RAZOO\QTP_Razoo_JSIssue\JSIssue]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[JSIssue]]></DName>
<Res><![CDATA[Res82]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[JavaScriptError]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Scenario</u>:</b> JavaScriptError<br><b><u>Defined in</u>:</b> RecoveryFiles\JSError.qrs<br><b><u>Loading failed with error</u>:</b> The path </div></SPAN>]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:02]]></Time>
<TimeTick>1308647162</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="5" status="Warning" nType="Recovery" >
<Disp><![CDATA[JavaScriptError]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:03]]></Time>
<TimeTick>1308647163</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:03]]></Time>
<TimeTick>1308647163</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Create.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:03]]></Time>
<TimeTick>1308647163</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="13" Source="Action1" SourceLine="318" >
<Disp><![CDATA[Create.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" Source="Action1" SourceLine="318" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:03]]></Time>
<TimeTick>1308647163</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="15" Source="Action1" SourceLine="319" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:06]]></Time>
<TimeTick>1308647166</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="17" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://www-qaindia.razoo.com/admin/verify_authorize_net_log<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:06]]></Time>
<TimeTick>1308647166</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" nType="Navigate to http://www-qaindia.razoo.com/admin/verify_authorize_net_log" Source="Action1" SourceLine="321" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:06]]></Time>
<TimeTick>1308647166</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" Source="Action1" SourceLine="324" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:09]]></Time>
<TimeTick>1308647169</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://www-qaindia.razoo.com/admin/guest_orders<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:09]]></Time>
<TimeTick>1308647169</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" nType="Navigate to https://www-qaindia.razoo.com/admin/guest_orders" Source="Action1" SourceLine="326" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:10]]></Time>
<TimeTick>1308647170</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="Action1" SourceLine="329" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:13]]></Time>
<TimeTick>1308647173</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="29" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://www-qaindia.razoo.com/admin/order_blacklists<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:13]]></Time>
<TimeTick>1308647173</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" nType="Navigate to https://www-qaindia.razoo.com/admin/order_blacklists" Source="Action1" SourceLine="331" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:13]]></Time>
<TimeTick>1308647173</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="33" Source="Action1" SourceLine="334" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:16]]></Time>
<TimeTick>1308647176</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://www-qaindia.razoo.com/admin/abingo_dashboard<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:16]]></Time>
<TimeTick>1308647176</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" nType="Navigate to http://www-qaindia.razoo.com/admin/abingo_dashboard" Source="Action1" SourceLine="336" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:16]]></Time>
<TimeTick>1308647176</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" Source="Action1" SourceLine="339" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:19]]></Time>
<TimeTick>1308647179</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="41" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://www-qaindia.razoo.com/team/new<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:19]]></Time>
<TimeTick>1308647179</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" nType="Navigate to https://www-qaindia.razoo.com/team/new" Source="Action1" SourceLine="343" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:19]]></Time>
<TimeTick>1308647179</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" Source="Action1" SourceLine="344" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:23]]></Time>
<TimeTick>1308647183</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:23]]></Time>
<TimeTick>1308647183</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[org_picker_kw.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Alliance Community Fund"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:23]]></Time>
<TimeTick>1308647183</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="51" Source="Action1" SourceLine="346" >
<Disp><![CDATA[org_picker_kw.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[campaign[title].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Champ Alli"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:23]]></Time>
<TimeTick>1308647183</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" Source="Action1" SourceLine="347" >
<Disp><![CDATA[campaign[title].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["WebElement"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (17 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=<br>html tag=SPAN<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (19 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=SPAN<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 18 matches)</SPAN><br>class=mceIcon mce_code<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:23]]></Time>
<TimeTick>1308647183</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="57" Source="Action1" SourceLine="348" >
<Disp><![CDATA["WebElement"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:23]]></Time>
<TimeTick>1308647183</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="58" Source="Action1" SourceLine="348" >
<Disp><![CDATA[WebElement.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="50" Source="Action1" SourceLine="346" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Action1" SourceLine="318" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[HTML Source Editor]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["HTML Source Editor"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=HTML Source Editor<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=HTML Source Editor<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=http://www-qaindia.razoo.com/javascripts/lib/tiny_mce/themes/advanced/source_editor.htm?16e1175be16c3e2afe14cc10770e6b395b1cf44c<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle={#advanced_dlg.code_title}<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasmenubar=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="61" Source="Action1" SourceLine="349" >
<Disp><![CDATA["HTML Source Editor"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[HTML Source Editor]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[htmlSource.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Story for FR Page"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" Source="Action1" SourceLine="349" >
<Disp><![CDATA[htmlSource.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Update.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" Source="Action1" SourceLine="350" >
<Disp><![CDATA[Update.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="63" Source="Action1" SourceLine="349" >
<Disp><![CDATA[HTML Source Editor]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="60" Source="Action1" SourceLine="349" >
<Disp><![CDATA[HTML Source Editor]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[campaign[goal_amount].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1000"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="72" Source="Action1" SourceLine="351" >
<Disp><![CDATA[campaign[goal_amount].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[campaign[start_at].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Jun 9, 2011"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" Source="Action1" SourceLine="352" >
<Disp><![CDATA[campaign[start_at].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[campaign[end_at].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Dec 31, 2011"]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="78" Source="Action1" SourceLine="353" >
<Disp><![CDATA[campaign[end_at].Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="71" Source="Action1" SourceLine="351" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="70" Source="Action1" SourceLine="351" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;campaign[designation]&quot; WebList object was not found in the Object Repository.<BR>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR>Line (355): &quot;Browser(&quot;An inspiring place to&quot;).Page(&quot;An inspiring place to&quot;).WebList(&quot;campaign[designation]&quot;).Select &quot;Other&quot;&quot;. ]]></Details>
<Time><![CDATA[6/21/2011 - 14:36:24]]></Time>
<TimeTick>1308647184</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="79" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;campaign[designation]&quot; WebList object was not found in the Object Repository.<BR>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR>Line (355): &quot;Browser(&quot;An inspiring place to&quot;).Page(&quot;An inspiring place to&quot;).WebList(&quot;campaign[designation]&quot;).Select &quot;Other&quot;&quot;. ]]></Details>
<Time><![CDATA[6/21/2011 - 14:37:10]]></Time>
<TimeTick>1308647230</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="80" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;campaign[designation]&quot; WebList object was not found in the Object Repository.<BR>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR>Line (355): &quot;Browser(&quot;An inspiring place to&quot;).Page(&quot;An inspiring place to&quot;).WebList(&quot;campaign[designation]&quot;).Select &quot;Other&quot;&quot;. ]]></Details>
<Time><![CDATA[6/21/2011 - 14:37:13]]></Time>
<TimeTick>1308647233</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="81" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;campaign[designation]&quot; WebList object was not found in the Object Repository.<BR>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR>Line (355): &quot;Browser(&quot;An inspiring place to&quot;).Page(&quot;An inspiring place to&quot;).WebList(&quot;campaign[designation]&quot;).Select &quot;Other&quot;&quot;. ]]></Details>
<Time><![CDATA[6/21/2011 - 14:37:14]]></Time>
<TimeTick>1308647234</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="82" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:38]]></Time>
<TimeTick>1308647318</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:38]]></Time>
<TimeTick>1308647318</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[campaign[designation]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the campaign[designation] object. Confirm that the specified item is included in the object's item collection.]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:38]]></Time>
<TimeTick>1308647318</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[campaign[designation]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>|Visible Items = 0<br>Visible = -1<br>Name = campaign[designation]<br>Items Count = 2<br>Html Id = campaign_designation<br>default value = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:38]]></Time>
<TimeTick>1308647318</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="92" status="Warning" nType="Description" Source="Action1" SourceLine="354" >
<Disp><![CDATA[campaign[designation]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="15" nRep="91" status="Failed" nType="Run Error" Source="Action1" SourceLine="354" >
<Disp><![CDATA[campaign[designation]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="90" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="89" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the campaign[designation] object. Confirm that the specified item is included in the object's item collection.<BR>Line (355): &quot;Browser(&quot;An inspiring place to&quot;).Page(&quot;An inspiring place to&quot;).WebList(&quot;campaign[designation]&quot;).Select &quot;Other&quot;&quot;. ]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:38]]></Time>
<TimeTick>1308647318</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="93" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:52]]></Time>
<TimeTick>1308647332</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:52]]></Time>
<TimeTick>1308647332</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[campaign[designation]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the campaign[designation] object. Confirm that the specified item is included in the object's item collection.]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:52]]></Time>
<TimeTick>1308647332</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[campaign[designation]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>|Visible Items = 0<br>Visible = -1<br>Name = campaign[designation]<br>Items Count = 2<br>Html Id = campaign_designation<br>default value = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:52]]></Time>
<TimeTick>1308647332</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="99" status="Warning" nType="Description" Source="Action1" SourceLine="354" >
<Disp><![CDATA[campaign[designation]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="15" nRep="98" status="Failed" nType="Run Error" Source="Action1" SourceLine="354" >
<Disp><![CDATA[campaign[designation]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="97" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="96" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the campaign[designation] object. Confirm that the specified item is included in the object's item collection.<BR>Line (355): &quot;Browser(&quot;An inspiring place to&quot;).Page(&quot;An inspiring place to&quot;).WebList(&quot;campaign[designation]&quot;).Select &quot;Other&quot;&quot;. ]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:52]]></Time>
<TimeTick>1308647332</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="100" status="Failed" Source="Action1" SourceLine="354" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:53]]></Time>
<TimeTick>1308647333</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/21/2011 - 14:38:53]]></Time>
<TimeTick>1308647333</TimeTick>
<Step rID="T57">