<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows 7" host="RAZOO-3"><DocLocation><![CDATA[D:\QTP_RAZOO\QTP_Razoo_JSIssue\JSIssue]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[JSIssue]]></DName>
<Res><![CDATA[Res58]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:49]]></Time>
<TimeTick>1307530729</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:49]]></Time>
<TimeTick>1307530729</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[fundraise > Start raising.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:49]]></Time>
<TimeTick>1307530729</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="Action1" SourceLine="114" >
<Disp><![CDATA[fundraise > Start raising.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Action1" SourceLine="114" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:49]]></Time>
<TimeTick>1307530729</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="14" Source="Action1" SourceLine="201" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:52]]></Time>
<TimeTick>1307530732</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="16" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://www-qaindia.razoo.com/admin<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:52]]></Time>
<TimeTick>1307530732</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" nType="Navigate to http://www-qaindia.razoo.com/admin" Source="Action1" SourceLine="203" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:52]]></Time>
<TimeTick>1307530732</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Action1" SourceLine="206" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:55]]></Time>
<TimeTick>1307530735</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://www-qaindia.razoo.com/homepage_marquees<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:55]]></Time>
<TimeTick>1307530735</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="24" nType="Navigate to http://www-qaindia.razoo.com/homepage_marquees" Source="Action1" SourceLine="208" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:55]]></Time>
<TimeTick>1307530735</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="Action1" SourceLine="213" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:58]]></Time>
<TimeTick>1307530738</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:58]]></Time>
<TimeTick>1307530738</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[New Marquee.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:58]]></Time>
<TimeTick>1307530738</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" Source="Action1" SourceLine="215" >
<Disp><![CDATA[New Marquee.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" Source="Action1" SourceLine="215" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/8/2011 - 16:28:58]]></Time>
<TimeTick>1307530738</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" Source="Action1" SourceLine="216" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:01]]></Time>
<TimeTick>1307530741</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:01]]></Time>
<TimeTick>1307530741</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:01]]></Time>
<TimeTick>1307530741</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Action1" SourceLine="218" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="39" Source="Action1" SourceLine="218" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://www-qaindia.razoo.com/admin/find_user<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:02]]></Time>
<TimeTick>1307530742</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="42" nType="Navigate to http://www-qaindia.razoo.com/admin/find_user" Source="Action1" SourceLine="222" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:02]]></Time>
<TimeTick>1307530742</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" Source="Action1" SourceLine="223" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:05]]></Time>
<TimeTick>1307530745</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://www-qaindia.razoo.com/admin/org_admins<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:05]]></Time>
<TimeTick>1307530745</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="48" nType="Navigate to https://www-qaindia.razoo.com/admin/org_admins" Source="Action1" SourceLine="228" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:06]]></Time>
<TimeTick>1307530746</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["HPRazoo3@sra.com"]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:06]]></Time>
<TimeTick>1307530746</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="Action1" SourceLine="229" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[ein.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123456789"]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:06]]></Time>
<TimeTick>1307530746</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="55" Source="Action1" SourceLine="230" >
<Disp><![CDATA[ein.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Create Admin.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:06]]></Time>
<TimeTick>1307530746</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="58" Source="Action1" SourceLine="231" >
<Disp><![CDATA[Create Admin.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="51" Source="Action1" SourceLine="229" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[msctls_statusbar32.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[100, 11]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:06]]></Time>
<TimeTick>1307530746</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" Source="Action1" SourceLine="232" >
<Disp><![CDATA[msctls_statusbar32.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:09]]></Time>
<TimeTick>1307530749</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="62" Source="Action1" SourceLine="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[An inspiring place to]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:30]]></Time>
<TimeTick>1307530770</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Manage Orders]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Manage Orders" (of class Link). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:30]]></Time>
<TimeTick>1307530770</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Manage Orders]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Link<br>Html Tag = A<br>|Visible = -1<br>Text = Manage Orders<br>Name = Manage Orders<br>Html Id = <br>Href = https://www-qa.razoo.com/admin/orders<br>DHTML Class = <br>]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:30]]></Time>
<TimeTick>1307530770</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="108" status="Warning" nType="Description" Source="Action1" SourceLine="237" >
<Disp><![CDATA[Manage Orders]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="107" status="Failed" nType="Run Error" Source="Action1" SourceLine="237" >
<Disp><![CDATA[Manage Orders]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="106" status="Failed" Source="Action1" SourceLine="237" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" status="Failed" Source="Action1" SourceLine="114" >
<Disp><![CDATA[An inspiring place to]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Manage Orders&quot; (of class Link). Verify that this object's properties match an object currently displayed in your application.<BR>Line (238): &quot;Browser(&quot;An inspiring place to&quot;).Page(&quot;An inspiring place to&quot;).Link(&quot;Manage Orders&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[6/8/2011 - 16:29:30]]></Time>
<TimeTick>1307530770</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="109" status="Failed" Source="Action1" SourceLine="237" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[6/8/2011 - 16:33:18]]></Time>
<TimeTick>1307530998</TimeTick>
<NodeArgs eType="General" icon="13" nRep="110" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/8/2011 - 16:28:49" eTime="6/8/2011 - 16:33:18" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[JSIssue Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[6/8/2011 - 16:33:18]]></Time>
<TimeTick>1307530998</TimeTick>
<NodeArgs eType="General" icon="14" nRep="113" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/8/2011 - 16:28:47" eTime="6/8/2011 - 16:33:18" passed="0" failed="2" warnings="1" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test JSIssue Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>